# Change these first
owner: konekoya # Your GitHub username
repo: konekoya-github-io-watcher # Your Github repository name

# Add your sites here
sites:
  - name: konekoya's website
    url: https://konekoya.github.io/
  - name: My blog
    url: https://konekoya.github.io/blog/
assignees: # Users to assign downtime issues (optional)
  - konekoya
status-website:
  baseUrl: /konekoya-github-io-watcher
  # where "repo" is your repository name
  name: Konekoya's site watcher
